# Generated by Django 4.2.6 on 2023-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0002_user_otp_user_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_trials_left',
            field=models.IntegerField(default=3),
        ),
    ]
