# Generated by Django 4.2.6 on 2023-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0003_user_free_trials_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
