# Generated by Django 4.2.6 on 2023-10-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(max_length=2000000)),
                ('special_words', models.CharField(blank=True, max_length=200, null=True)),
                ('interview_type', models.CharField(max_length=200)),
                ('interview_date', models.DateTimeField(auto_now_add=True)),
                ('interview_result', models.JSONField(blank=True, null=True)),
                ('interview_difficulty', models.CharField(max_length=2000)),
                ('interview_duration', models.CharField(max_length=2000)),
                ('interview_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_ready_app.user')),
            ],
        ),
    ]
