# Generated by Django 4.2.6 on 2023-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='prompt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
