# Generated by Django 4.2.6 on 2023-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0006_history_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interview_duration',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
