# Generated by Django 4.2.6 on 2023-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0007_alter_history_interview_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interview_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
