# Generated by Django 4.2.6 on 2023-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0008_alter_history_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
