# Generated by Django 4.2.6 on 2023-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0009_alter_history_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interview_duration',
            field=models.CharField(default='00:00:00', max_length=2000),
        ),
        migrations.AlterField(
            model_name='history',
            name='special_words',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
