# Generated by Django 4.2.6 on 2023-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0010_alter_history_interview_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='job_description',
            field=models.CharField(max_length=2000000),
        ),
    ]
