# Generated by Django 4.2.6 on 2023-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0011_alter_history_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interview_difficulty',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='history',
            name='interview_duration',
            field=models.CharField(default='00:00:00', max_length=20000),
        ),
    ]
