# Generated by Django 4.2.6 on 2023-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0012_alter_history_interview_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interview_type',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='history',
            name='prompt',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='special_words',
            field=models.CharField(default='None', max_length=20000),
        ),
    ]
