# Generated by Django 4.2.6 on 2023-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0013_alter_history_interview_type_alter_history_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
