# Generated by Django 4.2.6 on 2023-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_ready_app', '0014_history_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='overall_answer_score_based_on_question_according_to_interviewer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='overall_clarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='overall_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='overall_grammar',
            field=models.IntegerField(default=0),
        ),
    ]
